classDiagram
    class Context {
        -Strategy strategy
        +setStrategy(strategy)
        +doSomething()
    }

    class Strategy {
        <<Interface>>
        +execute(data)
    }

    class ConcreteStrategy {
        +execute(data)
    }

    class Client {
        +String featureDetails
        +requestApproval()
    }

    Context o-- Strategy
    Client ..>	ConcreteStrategy
    Client -->	Context
    ConcreteStrategy ..|> Strategy

    style ConcreteStrategy fill:#bfb,stroke:#6f6,stroke-width:2px,color:#000,stroke-dasharray: 5 5
    style Strategy fill:#9ff,stroke:#369,stroke-width:2px,color:#000,stroke-dasharray: 5 5
    style Context fill:#ffb,stroke:#663,stroke-width:2px,color:#000,stroke-dasharray: 5 5
    style Client fill:#ffb,stroke:#663,stroke-width:2px,color:#000,stroke-dasharray: 5 5
    style Context fill:#bfb,stroke:#6f6,stroke-width:2px,color:#000,stroke-dasharray: 5 5
